export const ANALYTICS = {
  panel: "analytics-panel",
  fromDate: "analytics-from-date",
  toDate: "analytics-to-date",
  applyBtn: "analytics-apply-btn",
  clearBtn: "analytics-clear-btn",
  marketFilter: "analytics-market-filter",
  userFilter: "analytics-user-filter",
  userSearch: "analytics-user-search",
  houseProfit: "analytics-house-profit",
  totalWagered: "analytics-total-wagered",
  totalReturned: "analytics-total-returned",
  dashboardHouseProfit: "dashboard-house-profit",
  dashboardSettledBets: "dashboard-settled-bets",
  dashboardWagered: "dashboard-wagered-24h",
  dashboardReturned: "dashboard-returned-24h",
  dashboardOpenExposure: "dashboard-open-exposure-24h",
  exportDailyBtn: "analytics-export-daily-btn",
  exportPlayersBtn: "analytics-export-players-btn",
  topPlayersTable: "analytics-top-players-table",
  viewUserPnlBtn: "analytics-view-user-pnl-btn",
};
